name: 🐛 Bug Report
description: File a bug report
title: "[🐛 Bug]: "
labels: [bug, needs-triaging]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Did you find something wrong with the Selenium site or the documentation? Please describe
        your finding in a clear and concise way.
      placeholder: |
        Please add as many details as possible to avoid assumptions from our side. How do you
        trigger this bug? What did you expect to happen? Please walk us through it step by step.
        If needed, please also add:
          * Absolute link where the issue was found
          * Screenshot (if needed)
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: What browsers and operating systems are you seeing the problem on?
      description: |
        Please add the browser, its version, and the operating system you are
        using to see this bug.
    validations:
      required: true
